create table public.authorized_emails (
  id uuid not null default gen_random_uuid (),
  email text not null,
  full_name text null,
  role text not null default 'assistant'::text,
  created_by uuid null,
  created_at timestamp with time zone null default now(),
  constraint authorized_emails_pkey primary key (id),
  constraint authorized_emails_email_key unique (email),
  constraint authorized_emails_created_by_fkey foreign KEY (created_by) references auth.users (id),
  -- Roles vigentes en la base de datos (verificado 2026-09-29): admin, dentist, assistant.
  constraint authorized_emails_role_check check ((role = any (array['admin'::text, 'dentist'::text, 'assistant'::text])))
) TABLESPACE pg_default;


create table public.clinical_histories (
  id bigint generated by default as identity not null,
  patient_id text not null,
  doctor text null,
  medio_remision text null,
  fecha timestamp with time zone not null default now(),
  motivo_consulta text null,
  history_data jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint clinical_histories_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists clinical_histories_patient_id_idx on public.clinical_histories using btree (patient_id) TABLESPACE pg_default;

create index IF not exists clinical_histories_fecha_idx on public.clinical_histories using btree (fecha desc) TABLESPACE pg_default;

create index IF not exists clinical_histories_patient_idx on public.clinical_histories using btree (patient_id) TABLESPACE pg_default;





------------------
create table public.doctors (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre text null,
  documento_identidad text null,
  updated_at timestamp with time zone not null default now(),
  apellidos text null,
  especialidad text null,
  correo text null,
  telefono text null,
  registro_profesional text null,
  activo boolean not null default true,
  observaciones text null,
  constraint doctors_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists doctors_documento_identidad_key on public.doctors using btree (documento_identidad) TABLESPACE pg_default;

create unique INDEX IF not exists doctors_correo_key on public.doctors using btree (correo) TABLESPACE pg_default
where
  (correo is not null);

create index IF not exists idx_doctors_nombre on public.doctors using btree (nombre) TABLESPACE pg_default;

create index IF not exists idx_doctors_activo on public.doctors using btree (activo) TABLESPACE pg_default;

create trigger trg_doctors_updated_at BEFORE
update on doctors for EACH row
execute FUNCTION set_updated_at ();


----------------------


create table public.inventory_items (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  name text not null,
  category text null,
  sku text null,
  stock numeric(12, 2) not null default 0,
  min_stock numeric(12, 2) not null default 0,
  unit text not null default 'unidad'::text,
  cost numeric(12, 2) not null default 0,
  supplier text null,
  expiration_date date null,
  active boolean not null default true,
  notes text null,
  constraint inventory_items_pkey primary key (id),
  constraint inventory_items_sku_key unique (sku),
  constraint inventory_items_cost_check check ((cost >= (0)::numeric)),
  constraint inventory_items_min_stock_check check ((min_stock >= (0)::numeric)),
  constraint inventory_items_stock_check check ((stock >= (0)::numeric))
) TABLESPACE pg_default;

create index IF not exists idx_inventory_items_name on public.inventory_items using btree (name) TABLESPACE pg_default;

create index IF not exists idx_inventory_items_category on public.inventory_items using btree (category) TABLESPACE pg_default;

create index IF not exists idx_inventory_items_stock on public.inventory_items using btree (stock) TABLESPACE pg_default;

create index IF not exists idx_inventory_items_active on public.inventory_items using btree (active) TABLESPACE pg_default;

create trigger trg_inventory_items_updated_at BEFORE
update on inventory_items for EACH row
execute FUNCTION set_updated_at ();


-------------------



create table public.laboratory_cases (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  patient_id uuid not null,
  procedure_catalog_id bigint null,
  doctor_id bigint null,
  work_name text not null,
  lab_name text null,
  due_date date null,
  received_date date null,
  delivered_date date null,
  status text not null default 'Pendiente'::text,
  notes text null,
  constraint laboratory_cases_pkey primary key (id),
  constraint laboratory_cases_doctor_id_fkey foreign KEY (doctor_id) references doctors (id) on delete set null,
  constraint laboratory_cases_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE,
  constraint laboratory_cases_procedure_catalog_id_fkey foreign KEY (procedure_catalog_id) references procedure_catalog (id) on delete set null,
  constraint laboratory_cases_status_check check (
    (
      status = any (
        array[
          'Pendiente'::text,
          'En proceso'::text,
          'Entregado'::text,
          'Cancelado'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_laboratory_cases_patient_id on public.laboratory_cases using btree (patient_id) TABLESPACE pg_default;

create index IF not exists idx_laboratory_cases_status on public.laboratory_cases using btree (status) TABLESPACE pg_default;

create index IF not exists idx_laboratory_cases_due_date on public.laboratory_cases using btree (due_date) TABLESPACE pg_default;

create index IF not exists laboratory_cases_patient_idx on public.laboratory_cases using btree (patient_id) TABLESPACE pg_default;

create trigger trg_laboratory_cases_updated_at BEFORE
update on laboratory_cases for EACH row
execute FUNCTION set_updated_at ();




-------------------


create table public.patient_procedures (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  patient_id uuid not null,
  procedure_catalog_id bigint not null,
  doctor_id bigint null,
  tooth_number text null,
  procedure_date date not null default CURRENT_DATE,
  status text not null default 'Pendiente'::text,
  quantity numeric(12, 2) not null default 1,
  unit_price numeric(12, 2) not null default 0,
  total_price numeric GENERATED ALWAYS as ((quantity * unit_price)) STORED (12, 2) null,
  notes text null,
  constraint patient_procedures_pkey primary key (id),
  constraint patient_procedures_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE,
  constraint patient_procedures_doctor_id_fkey foreign KEY (doctor_id) references doctors (id) on delete set null,
  constraint patient_procedures_procedure_catalog_id_fkey foreign KEY (procedure_catalog_id) references procedure_catalog (id),
  constraint patient_procedures_quantity_check check ((quantity > (0)::numeric)),
  constraint patient_procedures_status_check check (
    (
      status = any (
        array[
          'Pendiente'::text,
          'En proceso'::text,
          'Realizado'::text,
          'Cancelado'::text
        ]
      )
    )
  ),
  constraint patient_procedures_unit_price_check check ((unit_price >= (0)::numeric))
) TABLESPACE pg_default;

create index IF not exists idx_patient_procedures_patient_id on public.patient_procedures using btree (patient_id) TABLESPACE pg_default;

create index IF not exists idx_patient_procedures_procedure_catalog_id on public.patient_procedures using btree (procedure_catalog_id) TABLESPACE pg_default;

create index IF not exists idx_patient_procedures_procedure_date on public.patient_procedures using btree (procedure_date desc) TABLESPACE pg_default;

create index IF not exists idx_patient_procedures_status on public.patient_procedures using btree (status) TABLESPACE pg_default;

create trigger trg_patient_procedures_updated_at BEFORE
update on patient_procedures for EACH row
execute FUNCTION set_updated_at ();



--------------------




create table public.patients (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  nombre text null,
  apellidos text null,
  fecha_nacimiento date null,
  direccion text null,
  telefono text null,
  celular text null,
  ocupacion text null,
  sexo text null,
  email text null,
  tipo_sangre text null,
  eps text null,
  tipo_documento text not null,
  numero_documento text not null,
  acudiente_celular text null,
  acudiente_direccion text null,
  acudiente_nombre text null,
  acudiente_parentesco text null,
  edad text null,
  alergias text null,
  medicamentos text null,
  constraint patients_pkey primary key (id),
  -- La base de datos ya no tiene patients_tipo_documento_key (verificado 2026-09-29):
  -- varios pacientes pueden tener el mismo tipo de documento (p. ej. CC).
  constraint patients_numero_documento_key unique (numero_documento)
) TABLESPACE pg_default;

create index IF not exists patients_numero_documento_idx on public.patients using btree (numero_documento) TABLESPACE pg_default;

create trigger set_updated_at BEFORE
update on patients for EACH row
execute FUNCTION trg_set_updated_at ();






--------------------



create table public.procedure_catalog (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  code text null,
  name text not null,
  category text null,
  description text null,
  price numeric(12, 2) not null default 0,
  active boolean not null default true,
  constraint procedure_catalog_pkey primary key (id),
  constraint procedure_catalog_code_key unique (code),
  constraint procedure_catalog_price_check check ((price >= (0)::numeric))
) TABLESPACE pg_default;

create index IF not exists idx_procedure_catalog_name on public.procedure_catalog using btree (name) TABLESPACE pg_default;

create index IF not exists idx_procedure_catalog_active on public.procedure_catalog using btree (active) TABLESPACE pg_default;

create trigger trg_procedure_catalog_updated_at BEFORE
update on procedure_catalog for EACH row
execute FUNCTION set_updated_at ();




---------------------


create table public.procedures (
  id uuid not null default gen_random_uuid (),
  patient_id uuid not null,
  procedure_name text not null,
  tooth_number text null,
  cost numeric(10, 2) not null default 0,
  fecha date null default CURRENT_DATE,
  notes text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint procedures_pkey primary key (id),
  constraint procedures_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE,
  constraint procedures_cost_check check ((cost >= (0)::numeric))
) TABLESPACE pg_default;

create index IF not exists idx_procedures_patient_id on public.procedures using btree (patient_id) TABLESPACE pg_default;

create index IF not exists idx_procedures_created_at on public.procedures using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_procedures_name on public.procedures using btree (procedure_name) TABLESPACE pg_default;

create index IF not exists procedures_patient_idx on public.procedures using btree (patient_id) TABLESPACE pg_default;

create trigger trg_procedures_updated_at BEFORE
update on procedures for EACH row
execute FUNCTION set_updated_at ();


----------------------


create table public.profiles (
  id uuid not null,
  email text not null,
  full_name text null,
  role text not null default 'assistant'::text,
  created_at timestamp with time zone null default now(),
  constraint profiles_pkey primary key (id),
  constraint profiles_email_key unique (email),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint profiles_role_check check ((role = any (array['admin'::text, 'dentist'::text, 'assistant'::text])))
) TABLESPACE pg_default;

create unique INDEX IF not exists profiles_email_idx on public.profiles using btree (email) TABLESPACE pg_default;



-----------------------


create table public.radiographies (
  id serial not null,
  patient_id uuid null,
  file_path text null,
  file_name text null,
  description text null,
  metadata jsonb null,
  created_at timestamp with time zone not null default now(),
  constraint radiographies_pkey primary key (id),
  constraint radiographies_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists radiographies_patient_idx on public.radiographies using btree (patient_id) TABLESPACE pg_default;

-- Billing invoices table used by the Billing module
-- Includes optional patient_id (UUID FK) and patient_name for legacy/fallback uses
CREATE TABLE IF NOT EXISTS public.billing_invoices (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  patient_id uuid null,
  patient_document text null,
  patient_name text null,
  date date not null,
  amount numeric(12,2) not null default 0,
  status text not null default 'Pendiente'::text,
  metadata jsonb null,
  constraint billing_invoices_pkey primary key (id),
  constraint billing_invoices_status_check check (
    (
      status = any (array['Pagado'::text, 'Pendiente'::text, 'Anulado'::text])
    )
  ),
  constraint billing_invoices_patient_id_fkey foreign key (patient_id) references public.patients(id) on delete set null
);

alter table public.billing_invoices
  add column if not exists patient_document text null;

create index IF not exists idx_billing_invoices_patient_id on public.billing_invoices using btree (patient_id) TABLESPACE pg_default;
create index IF not exists idx_billing_invoices_date on public.billing_invoices using btree (date desc) TABLESPACE pg_default;

-- -----------------------
-- Correcciones añadidas: extensión, funciones de trigger, y ajuste de tipos/constraints
-- No se sobrescribieron líneas existentes; estas sentencias pueden ejecutarse de forma segura

-- Asegurar extensión necesaria para gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Función trigger para mantener updated_at sincronizado
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Alias histórico: algunos triggers llaman a `set_updated_at()`
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Corregir tipo de patient_id en clinical_histories (text -> uuid)
-- Esto asume que los valores existentes en patient_id son UUID en texto; si no, la conversión fallará.
ALTER TABLE public.clinical_histories
  ALTER COLUMN patient_id TYPE uuid USING patient_id::uuid;

-- Añadir la constraint FK si no existe
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'clinical_histories_patient_id_fkey'
      AND table_schema = 'public'
  ) THEN
    EXECUTE 'ALTER TABLE public.clinical_histories
      ADD CONSTRAINT clinical_histories_patient_id_fkey
      FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE';
  END IF;
END;
$$;

-- Nota: si se quiere que `radiographies.patient_id` sea NOT NULL, añade:
-- ALTER TABLE public.radiographies ALTER COLUMN patient_id SET NOT NULL;


-- 17/07/2026
ALTER TABLE public.authorized_emails
ADD COLUMN active boolean NOT NULL DEFAULT true;

-- -----------------------
-- 21/07/2026
-- Storage para radiografías
-- Crear un bucket para guardar archivos de radiografías
INSERT INTO storage.buckets (id, name, public)
VALUES ('radiographies', 'radiographies', true)
ON CONFLICT (id) DO UPDATE
SET public = EXCLUDED.public;

-- Permitir lectura a usuarios autenticados
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Allow authenticated read radiographies'
  ) THEN
    CREATE POLICY "Allow authenticated read radiographies"
    ON storage.objects
    FOR SELECT
    TO authenticated
    USING (bucket_id = 'radiographies');
  END IF;
END;
$$;

-- Permitir subida a usuarios autenticados
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Allow authenticated upload radiographies'
  ) THEN
    CREATE POLICY "Allow authenticated upload radiographies"
    ON storage.objects
    FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'radiographies');
  END IF;
END;
$$;

-- Permitir actualización y borrado si se necesita después
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Allow authenticated update radiographies'
  ) THEN
    CREATE POLICY "Allow authenticated update radiographies"
    ON storage.objects
    FOR UPDATE
    TO authenticated
    USING (bucket_id = 'radiographies')
    WITH CHECK (bucket_id = 'radiographies');
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Allow authenticated delete radiographies'
  ) THEN
    CREATE POLICY "Allow authenticated delete radiographies"
    ON storage.objects
    FOR DELETE
    TO authenticated
    USING (bucket_id = 'radiographies');
  END IF;
END;
$$;

-- 05/08/2026
-- Añadir columna odontograma a clinical_histories
ALTER TABLE clinical_histories ADD COLUMN odontograma JSONB;

-- 06/08/2026
-- Asociar cada radiografía a la historia clínica donde fue registrada
ALTER TABLE public.radiographies
  ADD COLUMN IF NOT EXISTS clinical_history_id bigint null;

CREATE INDEX IF NOT EXISTS radiographies_clinical_history_idx
  ON public.radiographies (clinical_history_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'radiographies_patient_id_fkey'
      AND table_schema = 'public'
  ) THEN
    ALTER TABLE public.radiographies
      ADD CONSTRAINT radiographies_patient_id_fkey
      FOREIGN KEY (patient_id)
      REFERENCES public.patients(id)
      ON DELETE CASCADE;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'radiographies_clinical_history_id_fkey'
      AND table_schema = 'public'
  ) THEN
    ALTER TABLE public.radiographies
      ADD CONSTRAINT radiographies_clinical_history_id_fkey
      FOREIGN KEY (clinical_history_id)
      REFERENCES public.clinical_histories(id)
      ON DELETE CASCADE;
  END IF;
END;
$$;


----------------------


create table public.message_templates (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  channel text not null default 'Email',
  subject text null,
  body text not null,
  active boolean not null default true,
  constraint message_templates_pkey primary key (id),
  constraint message_templates_channel_check check (channel = any (array['Email'::text,'SMS'::text,'WhatsApp'::text]))
) TABLESPACE pg_default;

create trigger trg_message_templates_updated_at
before update on public.message_templates
for each row execute function set_updated_at();

alter table public.message_templates enable row level security;

create policy message_templates_all_authenticated
on public.message_templates
for all
to authenticated
using (true)
with check (true);


----------------------


create table public.informed_consents (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  patient_id uuid not null,
  doctor_id bigint null,
  procedure_catalog_id bigint null,
  content text not null,
  patient_signature_name text not null,
  signed_at timestamptz not null default now(),
  registered_by uuid null,
  constraint informed_consents_pkey primary key (id),
  constraint informed_consents_patient_id_fkey foreign key (patient_id) references public.patients (id) on delete cascade,
  constraint informed_consents_doctor_id_fkey foreign key (doctor_id) references public.doctors (id) on delete set null,
  constraint informed_consents_procedure_catalog_id_fkey foreign key (procedure_catalog_id) references public.procedure_catalog (id) on delete set null,
  constraint informed_consents_registered_by_fkey foreign key (registered_by) references auth.users (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_informed_consents_patient_id on public.informed_consents using btree (patient_id) TABLESPACE pg_default;

alter table public.informed_consents enable row level security;

create policy informed_consents_all_authenticated
on public.informed_consents
for all
to authenticated
using (true)
with check (true);


----------------------


create table public.data_rectification_requests (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  patient_id uuid not null,
  request_type text not null default 'Rectificación',
  description text not null,
  status text not null default 'Pendiente',
  resolution_notes text null,
  resolved_at timestamptz null,
  constraint data_rectification_requests_pkey primary key (id),
  constraint data_rectification_requests_patient_id_fkey foreign key (patient_id) references public.patients (id) on delete cascade,
  constraint data_rectification_requests_type_check check (request_type = any (array['Rectificación'::text,'Actualización'::text,'Supresión'::text,'Revocatoria de autorización'::text])),
  constraint data_rectification_requests_status_check check (status = any (array['Pendiente'::text,'En proceso'::text,'Resuelta'::text,'Rechazada'::text]))
) TABLESPACE pg_default;

create index IF not exists idx_data_rectification_requests_patient_id on public.data_rectification_requests using btree (patient_id) TABLESPACE pg_default;

create trigger trg_data_rectification_requests_updated_at
before update on public.data_rectification_requests
for each row execute function set_updated_at();

alter table public.data_rectification_requests enable row level security;

create policy data_rectification_requests_all_authenticated
on public.data_rectification_requests
for all
to authenticated
using (true)
with check (true);


----------------------


-- CU-20: autorizacion de tratamiento de datos personales, capturada en el registro del paciente
alter table public.patients
  add column if not exists autorizacion_datos boolean not null default false,
  add column if not exists autorizacion_datos_fecha timestamptz null;


----------------------


-- system_settings (tabla preexistente, definicion documentada aqui por primera vez)
-- create table public.system_settings (
--   id bigint generated by default as identity not null,
--   appointment_duration_minutes integer not null default 20,
--   business_hours_start time without time zone not null default '08:00:00',
--   business_hours_end time without time zone not null default '18:00:00',
--   updated_at timestamptz not null default now(),
--   constraint system_settings_pkey primary key (id)
-- );

-- RLS estaba deshabilitado (tabla totalmente expuesta a anon/authenticated). Se habilito
-- con el mismo patron "authenticated, ALL" usado en el resto del esquema.
alter table public.system_settings enable row level security;

create policy system_settings_all_authenticated
on public.system_settings
for all
to authenticated
using (true)
with check (true);


----------------------


-- CU-06/07/08/17/22: espejo de citas de Google Calendar en Supabase. Las citas viven
-- en Google Calendar (unica fuente de verdad para horarios); esta tabla existe porque
-- ningun proceso de servidor (cron/Edge Function) puede leer Google Calendar sin un
-- refresh token persistido, que hoy no se guarda en ningun lado (solo existe
-- session.provider_token, efimero, en el navegador de quien inicio sesion). Se
-- sincroniza en el cliente (CalendarCtrl.js) cada vez que se crea/reprograma/cancela
-- una cita desde la app, y directamente desde el webhook de WhatsApp para
-- solicitudes/cancelaciones que aun no existen en Google Calendar.
create extension if not exists pg_cron;
create extension if not exists pg_net;

create table public.appointments (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  patient_id uuid null,
  google_event_id text null,
  start_at timestamptz null,
  end_at timestamptz null,
  service_type text null,
  notes text null,
  status text not null default 'Confirmada',
  source text not null default 'App',
  requester_phone text null,
  reminder_sent_at timestamptz null,
  constraint appointments_pkey primary key (id),
  constraint appointments_google_event_id_key unique (google_event_id),
  constraint appointments_patient_id_fkey foreign key (patient_id) references public.patients (id) on delete set null,
  constraint appointments_status_check check (status = any (array['Solicitada'::text,'Confirmada'::text,'Cancelación solicitada'::text,'Cancelada'::text])),
  constraint appointments_source_check check (source = any (array['App'::text,'WhatsApp'::text]))
) TABLESPACE pg_default;

create index IF not exists idx_appointments_patient_id on public.appointments using btree (patient_id) TABLESPACE pg_default;
create index IF not exists idx_appointments_start_at on public.appointments using btree (start_at) TABLESPACE pg_default;
create index IF not exists idx_appointments_status on public.appointments using btree (status) TABLESPACE pg_default;

create trigger trg_appointments_updated_at
before update on public.appointments
for each row execute function set_updated_at();

alter table public.appointments enable row level security;

create policy appointments_all_authenticated
on public.appointments
for all
to authenticated
using (true)
with check (true);


----------------------


-- CU-16/17/21/22/23: bitacora de mensajes de WhatsApp (entrantes y salientes). Cualquier
-- parte de la app que necesite enviar un mensaje inserta una fila 'outbound'/'pending' aqui;
-- la Edge Function process-whatsapp-queue (cron cada 5 min) la entrega via Twilio cuando
-- haya credenciales configuradas, o la marca 'no_provider' si no las hay.
create table public.whatsapp_messages (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  sent_at timestamptz null,
  direction text not null,
  phone text not null,
  patient_id uuid null,
  appointment_id bigint null,
  template_id bigint null,
  body text not null,
  status text not null default 'pending',
  provider_message_id text null,
  error text null,
  constraint whatsapp_messages_pkey primary key (id),
  constraint whatsapp_messages_patient_id_fkey foreign key (patient_id) references public.patients (id) on delete set null,
  constraint whatsapp_messages_appointment_id_fkey foreign key (appointment_id) references public.appointments (id) on delete set null,
  constraint whatsapp_messages_template_id_fkey foreign key (template_id) references public.message_templates (id) on delete set null,
  constraint whatsapp_messages_direction_check check (direction = any (array['inbound'::text,'outbound'::text])),
  constraint whatsapp_messages_status_check check (status = any (array['pending'::text,'sent'::text,'failed'::text,'received'::text,'no_provider'::text]))
) TABLESPACE pg_default;

create index IF not exists idx_whatsapp_messages_status on public.whatsapp_messages using btree (status) TABLESPACE pg_default;
create index IF not exists idx_whatsapp_messages_phone on public.whatsapp_messages using btree (phone) TABLESPACE pg_default;
create index IF not exists idx_whatsapp_messages_patient_id on public.whatsapp_messages using btree (patient_id) TABLESPACE pg_default;

alter table public.whatsapp_messages enable row level security;

create policy whatsapp_messages_all_authenticated
on public.whatsapp_messages
for all
to authenticated
using (true)
with check (true);

-- Cron: dispara las Edge Functions desplegadas en supabase/functions/*.
-- queue-appointment-reminders: cada hora, revisa citas confirmadas 23-25h en el futuro
--   sin recordatorio enviado y encola un mensaje en whatsapp_messages.
-- process-whatsapp-queue: cada 5 minutos, entrega los mensajes 'pending' via Twilio.
-- Ambas usan la anon key (JWT publico) porque las funciones corren con verify_jwt=true
-- y usan SUPABASE_SERVICE_ROLE_KEY (inyectada automaticamente por Supabase) por dentro
-- para saltarse RLS.
select cron.schedule(
  'queue-appointment-reminders',
  '0 * * * *',
  $$
  select net.http_post(
    url := 'https://czfuquhkjuhbwnkbgkze.supabase.co/functions/v1/queue-appointment-reminders',
    headers := '{"Authorization": "Bearer <anon key>", "Content-Type": "application/json"}'::jsonb,
    body := '{}'::jsonb
  );
  $$
);

select cron.schedule(
  'process-whatsapp-queue',
  '*/5 * * * *',
  $$
  select net.http_post(
    url := 'https://czfuquhkjuhbwnkbgkze.supabase.co/functions/v1/process-whatsapp-queue',
    headers := '{"Authorization": "Bearer <anon key>", "Content-Type": "application/json"}'::jsonb,
    body := '{}'::jsonb
  );
  $$
);


----------------------


-- Correcciones de seguridad y rendimiento (advisors de Supabase), 2026-09-27.

-- BUG activo: 'doctors' y 'patient_procedures' tenian RLS habilitado sin ninguna
-- politica, lo que ocultaba silenciosamente TODOS sus datos (sin error) a
-- cualquier usuario autenticado. Afectaba la pestaña "Tratamientos y
-- odontograma" en PatientDetailVW.jsx (CU-10).
create policy doctors_all_authenticated
on public.doctors
for all
to authenticated
using (true)
with check (true);

create policy patient_procedures_all_authenticated
on public.patient_procedures
for all
to authenticated
using (true)
with check (true);

-- Endurecimiento de funciones: search_path fijo (evita hijacking via search_path)
-- y se revoca el EXECUTE publico sobre handle_new_user (solo debe dispararse
-- como trigger de auth.users, no ser invocable via RPC).
alter function public.handle_new_user() set search_path = '';
alter function public.set_updated_at() set search_path = '';
alter function public.trg_set_updated_at() set search_path = '';
revoke execute on function public.handle_new_user() from public, anon, authenticated;

-- Rendimiento de RLS: cachear auth.uid()/auth.jwt() por sentencia en vez de
-- reevaluarlos por fila (patron recomendado por Supabase). Tambien se eliminan
-- las 4 politicas legacy de clinical_histories que quedaban redundantes frente
-- a las politicas "..._authenticated" (permisivas OR, sin restriccion real).
drop policy if exists "Authenticated staff can view clinical histories" on public.clinical_histories;
drop policy if exists "Authenticated staff can insert clinical histories" on public.clinical_histories;
drop policy if exists "Authenticated staff can update clinical histories" on public.clinical_histories;
drop policy if exists "Authenticated staff can delete clinical histories" on public.clinical_histories;

alter policy "Allow read for authenticated users" on public.patients
  using ((select auth.uid()) is not null);
alter policy "Allow update for authenticated users" on public.patients
  using ((select auth.uid()) is not null);
alter policy "Allow delete for authenticated users" on public.patients
  using ((select auth.uid()) is not null);

alter policy "Admin manage authorized emails" on public.authorized_emails
  using (exists (select 1 from profiles where profiles.id = (select auth.uid()) and profiles.role = 'admin'::text));
alter policy "Users can check their own authorization" on public.authorized_emails
  using (email = ((select auth.jwt()) ->> 'email'::text));

alter policy "select_own_profile" on public.profiles
  using ((select auth.uid()) = id);
alter policy "update_own_profile" on public.profiles
  using ((select auth.uid()) = id);
alter policy "insert_own_profile" on public.profiles
  with check ((select auth.uid()) = id);

-- Indices duplicados (mismo par de columnas que otro indice existente).
drop index if exists public.clinical_histories_patient_idx;
drop index if exists public.laboratory_cases_patient_idx;
drop index if exists public.procedures_patient_idx;
drop index if exists public.profiles_email_idx;

-- Foreign keys sin indice de cobertura (impacta joins/deletes en cascada).
create index if not exists idx_authorized_emails_created_by on public.authorized_emails (created_by);
create index if not exists idx_informed_consents_doctor_id on public.informed_consents (doctor_id);
create index if not exists idx_informed_consents_procedure_catalog_id on public.informed_consents (procedure_catalog_id);
create index if not exists idx_informed_consents_registered_by on public.informed_consents (registered_by);
create index if not exists idx_laboratory_cases_doctor_id on public.laboratory_cases (doctor_id);
create index if not exists idx_laboratory_cases_procedure_catalog_id on public.laboratory_cases (procedure_catalog_id);
create index if not exists idx_patient_procedures_doctor_id on public.patient_procedures (doctor_id);
create index if not exists idx_whatsapp_messages_appointment_id on public.whatsapp_messages (appointment_id);
create index if not exists idx_whatsapp_messages_template_id on public.whatsapp_messages (template_id);

-- CU-08 (flujo alternativo ROC-13): estado 'No asistida' para citas a las que el paciente no llego.
alter table public.appointments drop constraint appointments_status_check;
alter table public.appointments add constraint appointments_status_check
  check (status = any (array['Solicitada'::text,'Confirmada'::text,'Cancelación solicitada'::text,'Cancelada'::text,'No asistida'::text]));

-- NO corregido (requiere accion manual fuera de SQL):
-- 1) Extension pg_net registrada en esquema 'public': la extension no soporta
--    ALTER EXTENSION ... SET SCHEMA. Sus funciones (net.http_post, etc.) ya
--    viven aisladas en su propio esquema 'net', asi que el riesgo real es bajo;
--    forzar una recreacion arriesgaba romper los cron jobs activos.
-- 2) "Leaked password protection" deshabilitado en Auth: no es configuracion
--    de Postgres, se activa en el Dashboard de Supabase en
--    Authentication > Policies > Password Security.
-- 3) 'authorized_emails' sigue con 2 politicas permisivas para SELECT
--    (admin ve todo + cada usuario ve su propio correo): es una decision de
--    diseño (dos audiencias distintas), no una redundancia real, asi que se
--    dejo tal cual en vez de forzar una fusion que complicaria la logica.


----------------------


-- Migracion thesis_points_1_to_5_soft_delete_annul (aplicada 2026-09-29).
-- Ley 38 de 1993 / Resolucion 839 de 2017: los pacientes se inactivan y las
-- atenciones y radiografias se anulan con nota; nada de esto se borra.

-- CU-05: inactivar pacientes en vez de borrarlos.
alter table public.patients add column if not exists activo boolean not null default true;
create index if not exists idx_patients_activo on public.patients(activo);

-- CU-20: medio por el que el paciente dio la autorizacion de datos.
alter table public.patients add column if not exists autorizacion_datos_medio text;
alter table public.patients add constraint patients_autorizacion_datos_medio_check
  check (autorizacion_datos_medio is null or autorizacion_datos_medio in ('presencial','whatsapp','email','telefono','otro'));

-- CU-09: anular atenciones clinicas y radiografias.
alter table public.clinical_histories
  add column if not exists anulada boolean not null default false,
  add column if not exists motivo_anulacion text,
  add column if not exists anulada_por uuid references auth.users(id),
  add column if not exists anulada_at timestamptz;
alter table public.radiographies
  add column if not exists anulada boolean not null default false,
  add column if not exists motivo_anulacion text,
  add column if not exists anulada_por uuid references auth.users(id),
  add column if not exists anulada_at timestamptz;
create index if not exists idx_clinical_histories_anulada on public.clinical_histories(anulada);
create index if not exists idx_radiographies_anulada on public.radiographies(anulada);
create index if not exists idx_clinical_histories_anulada_por on public.clinical_histories(anulada_por);
create index if not exists idx_radiographies_anulada_por on public.radiographies(anulada_por);

-- La base de datos no deja borrar un paciente que tenga registros clinicos.
alter table public.clinical_histories drop constraint clinical_histories_patient_id_fkey,
  add constraint clinical_histories_patient_id_fkey foreign key (patient_id) references public.patients(id) on delete restrict;
alter table public.radiographies drop constraint radiographies_patient_id_fkey,
  add constraint radiographies_patient_id_fkey foreign key (patient_id) references public.patients(id) on delete restrict;
alter table public.patient_procedures drop constraint patient_procedures_patient_id_fkey,
  add constraint patient_procedures_patient_id_fkey foreign key (patient_id) references public.patients(id) on delete restrict;
alter table public.laboratory_cases drop constraint laboratory_cases_patient_id_fkey,
  add constraint laboratory_cases_patient_id_fkey foreign key (patient_id) references public.patients(id) on delete restrict;

create or replace function public.set_anulada_timestamp()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.anulada and not old.anulada then
    new.anulada_at := now();
  end if;
  return new;
end;
$$;
create trigger trg_clinical_histories_anulada_at before update on public.clinical_histories
  for each row execute function public.set_anulada_timestamp();
create trigger trg_radiographies_anulada_at before update on public.radiographies
  for each row execute function public.set_anulada_timestamp();


----------------------


-- Migracion thesis_plans_consent_inventory_billing (2026-09-29).
-- CU-10 planes de tratamiento, CU-18 consentimiento ligado al plan, CU-11 descuento de
-- inventario por tratamiento, CU-12 laboratorio ligado al tratamiento y CU-13/CU-14
-- facturas con items, pagos parciales y anulacion (las facturas ya no se borran).

-- CU-10: planes de tratamiento. Un plan agrupa los tratamientos (patient_procedures)
-- de un paciente, queda asociado a una historia clinica y permanece 'Abierto' hasta
-- que se cierra (ROC-18). No se borran: se cierran o se cancelan con nota.
create table public.treatment_plans (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  patient_id uuid not null,
  clinical_history_id bigint null,
  doctor_id bigint null,
  title text not null,
  diagnosis text null,
  notes text null,
  status text not null default 'Abierto',
  start_date date not null default current_date,
  closed_at timestamptz null,
  closing_notes text null,
  created_by uuid null default auth.uid(),
  constraint treatment_plans_pkey primary key (id),
  constraint treatment_plans_patient_id_fkey foreign key (patient_id) references public.patients (id) on delete restrict,
  constraint treatment_plans_clinical_history_id_fkey foreign key (clinical_history_id) references public.clinical_histories (id) on delete restrict,
  constraint treatment_plans_doctor_id_fkey foreign key (doctor_id) references public.doctors (id) on delete set null,
  constraint treatment_plans_created_by_fkey foreign key (created_by) references auth.users (id) on delete set null,
  constraint treatment_plans_status_check check (status = any (array['Abierto'::text,'Cerrado'::text,'Cancelado'::text]))
);
create index idx_treatment_plans_patient_id on public.treatment_plans (patient_id);
create index idx_treatment_plans_clinical_history_id on public.treatment_plans (clinical_history_id);
create index idx_treatment_plans_doctor_id on public.treatment_plans (doctor_id);
create index idx_treatment_plans_created_by on public.treatment_plans (created_by);

create trigger trg_treatment_plans_updated_at before update on public.treatment_plans
  for each row execute function public.set_updated_at();

create or replace function public.set_treatment_plan_closed_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.status <> 'Abierto' and old.status = 'Abierto' then
    new.closed_at := now();
  elsif new.status = 'Abierto' and old.status <> 'Abierto' then
    new.closed_at := null;
  end if;
  return new;
end;
$$;
create trigger trg_treatment_plans_closed_at before update on public.treatment_plans
  for each row execute function public.set_treatment_plan_closed_at();

alter table public.treatment_plans enable row level security;
create policy treatment_plans_select_authenticated on public.treatment_plans for select to authenticated using (true);
create policy treatment_plans_insert_authenticated on public.treatment_plans for insert to authenticated with check (true);
create policy treatment_plans_update_authenticated on public.treatment_plans for update to authenticated using (true) with check (true);

alter table public.patient_procedures
  add column treatment_plan_id bigint null,
  add constraint patient_procedures_treatment_plan_id_fkey foreign key (treatment_plan_id) references public.treatment_plans (id) on delete restrict;
create index idx_patient_procedures_treatment_plan_id on public.patient_procedures (treatment_plan_id);


-- CU-18: el consentimiento queda ligado al plan. aceptado = false registra la negativa
-- del paciente (flujo alternativo). El consentimiento es un registro legal: el paciente
-- ya no puede borrarse en cascada con sus consentimientos.
alter table public.informed_consents
  add column treatment_plan_id bigint null,
  add column aceptado boolean not null default true,
  add constraint informed_consents_treatment_plan_id_fkey foreign key (treatment_plan_id) references public.treatment_plans (id) on delete restrict;
create index idx_informed_consents_treatment_plan_id on public.informed_consents (treatment_plan_id);
alter table public.informed_consents drop constraint informed_consents_patient_id_fkey,
  add constraint informed_consents_patient_id_fkey foreign key (patient_id) references public.patients (id) on delete restrict;

-- Un tratamiento de un plan solo se agrega a un plan abierto del mismo paciente, y
-- solo se marca 'Realizado' si el ultimo consentimiento del plan fue aceptado.
create or replace function public.check_patient_procedure_plan()
returns trigger language plpgsql set search_path = '' as $$
declare
  v_plan public.treatment_plans;
  v_accepted boolean;
begin
  if new.treatment_plan_id is null then
    return new;
  end if;

  select * into v_plan from public.treatment_plans where id = new.treatment_plan_id;
  if v_plan.patient_id <> new.patient_id then
    raise exception 'El plan de tratamiento pertenece a otro paciente.';
  end if;
  if tg_op = 'INSERT' and v_plan.status <> 'Abierto' then
    raise exception 'El plan de tratamiento está %: no se le pueden agregar tratamientos.', lower(v_plan.status);
  end if;

  if new.status = 'Realizado' and (tg_op = 'INSERT' or old.status is distinct from 'Realizado') then
    select c.aceptado into v_accepted
    from public.informed_consents c
    where c.treatment_plan_id = new.treatment_plan_id
    order by c.signed_at desc, c.id desc
    limit 1;
    if v_accepted is null then
      raise exception 'El plan no tiene consentimiento informado: regístralo antes de marcar tratamientos como realizados.';
    elsif not v_accepted then
      raise exception 'El paciente no aceptó el consentimiento de este plan: el tratamiento no se puede realizar.';
    end if;
  end if;

  return new;
end;
$$;
create trigger trg_patient_procedures_plan before insert or update on public.patient_procedures
  for each row execute function public.check_patient_procedure_plan();


-- CU-11: materiales de inventario que consume cada tratamiento. El stock se descuenta
-- cuando el tratamiento pasa a 'Realizado' (o al agregar el material a un tratamiento
-- ya realizado) y se repone si el tratamiento deja de estar realizado.
create table public.treatment_inventory_items (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  patient_procedure_id bigint not null,
  inventory_item_id bigint not null,
  quantity numeric(12, 2) not null,
  deducted_at timestamptz null,
  constraint treatment_inventory_items_pkey primary key (id),
  constraint treatment_inventory_items_procedure_item_key unique (patient_procedure_id, inventory_item_id),
  constraint treatment_inventory_items_patient_procedure_id_fkey foreign key (patient_procedure_id) references public.patient_procedures (id) on delete restrict,
  constraint treatment_inventory_items_inventory_item_id_fkey foreign key (inventory_item_id) references public.inventory_items (id) on delete restrict,
  constraint treatment_inventory_items_quantity_check check (quantity > (0)::numeric)
);
create index idx_treatment_inventory_items_inventory_item_id on public.treatment_inventory_items (inventory_item_id);

alter table public.treatment_inventory_items enable row level security;
create policy treatment_inventory_items_select_authenticated on public.treatment_inventory_items for select to authenticated using (true);
create policy treatment_inventory_items_insert_authenticated on public.treatment_inventory_items for insert to authenticated with check (true);
create policy treatment_inventory_items_delete_authenticated on public.treatment_inventory_items for delete to authenticated using (true);

create or replace function public.deduct_inventory_stock(p_item_id bigint, p_quantity numeric)
returns void language plpgsql set search_path = '' as $$
declare
  v_item public.inventory_items;
begin
  select * into v_item from public.inventory_items where id = p_item_id for update;
  if v_item.stock < p_quantity then
    raise exception 'Stock insuficiente de "%": hay % %, el tratamiento requiere %.',
      v_item.name, v_item.stock, v_item.unit, p_quantity;
  end if;
  update public.inventory_items set stock = stock - p_quantity where id = p_item_id;
end;
$$;

create or replace function public.apply_procedure_inventory()
returns trigger language plpgsql set search_path = '' as $$
declare
  r record;
begin
  if new.status = 'Realizado' and old.status is distinct from 'Realizado' then
    for r in
      select id, inventory_item_id, quantity from public.treatment_inventory_items
      where patient_procedure_id = new.id and deducted_at is null
    loop
      perform public.deduct_inventory_stock(r.inventory_item_id, r.quantity);
      update public.treatment_inventory_items set deducted_at = now() where id = r.id;
    end loop;
  elsif old.status = 'Realizado' and new.status <> 'Realizado' then
    update public.inventory_items i set stock = i.stock + t.quantity
    from public.treatment_inventory_items t
    where t.patient_procedure_id = new.id and t.deducted_at is not null and i.id = t.inventory_item_id;
    update public.treatment_inventory_items set deducted_at = null
    where patient_procedure_id = new.id and deducted_at is not null;
  end if;
  return new;
end;
$$;
create trigger trg_patient_procedures_inventory after update of status on public.patient_procedures
  for each row execute function public.apply_procedure_inventory();

create or replace function public.treatment_inventory_item_changes()
returns trigger language plpgsql set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    if old.deducted_at is not null then
      raise exception 'Este material ya se descontó del inventario: no se puede quitar del tratamiento.';
    end if;
    return old;
  end if;

  if (select status from public.patient_procedures where id = new.patient_procedure_id) = 'Realizado' then
    perform public.deduct_inventory_stock(new.inventory_item_id, new.quantity);
    new.deducted_at := now();
  else
    new.deducted_at := null;
  end if;
  return new;
end;
$$;
create trigger trg_treatment_inventory_items_changes before insert or delete on public.treatment_inventory_items
  for each row execute function public.treatment_inventory_item_changes();


-- CU-12: el trabajo de laboratorio puede ligarse al tratamiento que lo origina.
alter table public.laboratory_cases
  add column patient_procedure_id bigint null,
  add constraint laboratory_cases_patient_procedure_id_fkey foreign key (patient_procedure_id) references public.patient_procedures (id) on delete set null;
create index idx_laboratory_cases_patient_procedure_id on public.laboratory_cases (patient_procedure_id);


-- CU-13/CU-14: facturas con items ligados a tratamientos realizados, pagos (totales o
-- parciales) y anulacion con motivo. El estado de la factura (Pendiente / Parcial /
-- Pagado) lo calcula la base de datos a partir de los pagos no anulados; 'Anulado' solo
-- se alcanza anulando con motivo. Facturas, items y pagos no se borran.
alter table public.billing_invoices drop constraint billing_invoices_status_check,
  add constraint billing_invoices_status_check
  check (status = any (array['Pendiente'::text,'Parcial'::text,'Pagado'::text,'Anulado'::text]));
alter table public.billing_invoices
  add column motivo_anulacion text null,
  add column anulada_por uuid null,
  add column anulada_at timestamptz null,
  add constraint billing_invoices_anulada_por_fkey foreign key (anulada_por) references auth.users (id) on delete set null;
create index idx_billing_invoices_anulada_por on public.billing_invoices (anulada_por);

create table public.invoice_items (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  invoice_id bigint not null,
  patient_procedure_id bigint null,
  description text not null,
  quantity numeric(12, 2) not null default 1,
  unit_price numeric(12, 2) not null default 0,
  total numeric(12, 2) generated always as (quantity * unit_price) stored,
  constraint invoice_items_pkey primary key (id),
  constraint invoice_items_invoice_id_fkey foreign key (invoice_id) references public.billing_invoices (id) on delete restrict,
  constraint invoice_items_patient_procedure_id_fkey foreign key (patient_procedure_id) references public.patient_procedures (id) on delete restrict,
  constraint invoice_items_quantity_check check (quantity > (0)::numeric),
  constraint invoice_items_unit_price_check check (unit_price >= (0)::numeric)
);
create index idx_invoice_items_invoice_id on public.invoice_items (invoice_id);
create index idx_invoice_items_patient_procedure_id on public.invoice_items (patient_procedure_id);

alter table public.invoice_items enable row level security;
create policy invoice_items_select_authenticated on public.invoice_items for select to authenticated using (true);
create policy invoice_items_insert_authenticated on public.invoice_items for insert to authenticated with check (true);

create or replace function public.check_invoice_item()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.patient_procedure_id is null then
    return new;
  end if;
  if (select status from public.patient_procedures where id = new.patient_procedure_id) is distinct from 'Realizado' then
    raise exception 'Solo se facturan tratamientos realizados.';
  end if;
  if exists (
    select 1 from public.invoice_items ii
    join public.billing_invoices b on b.id = ii.invoice_id
    where ii.patient_procedure_id = new.patient_procedure_id and b.status <> 'Anulado'
  ) then
    raise exception 'Este tratamiento ya está incluido en otra factura vigente.';
  end if;
  return new;
end;
$$;
create trigger trg_invoice_items_check before insert on public.invoice_items
  for each row execute function public.check_invoice_item();

create table public.payments (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  invoice_id bigint not null,
  amount numeric(12, 2) not null,
  paid_at date not null default current_date,
  method text not null default 'Efectivo',
  reference text null,
  notes text null,
  registered_by uuid null default auth.uid(),
  anulado boolean not null default false,
  motivo_anulacion text null,
  anulado_por uuid null,
  anulado_at timestamptz null,
  constraint payments_pkey primary key (id),
  constraint payments_invoice_id_fkey foreign key (invoice_id) references public.billing_invoices (id) on delete restrict,
  constraint payments_registered_by_fkey foreign key (registered_by) references auth.users (id) on delete set null,
  constraint payments_anulado_por_fkey foreign key (anulado_por) references auth.users (id) on delete set null,
  constraint payments_amount_check check (amount > (0)::numeric),
  constraint payments_method_check check (method = any (array['Efectivo'::text,'Tarjeta'::text,'Transferencia'::text,'Otro'::text]))
);
create index idx_payments_invoice_id on public.payments (invoice_id);
create index idx_payments_registered_by on public.payments (registered_by);
create index idx_payments_anulado_por on public.payments (anulado_por);

alter table public.payments enable row level security;
create policy payments_select_authenticated on public.payments for select to authenticated using (true);
create policy payments_insert_authenticated on public.payments for insert to authenticated with check (true);
create policy payments_update_authenticated on public.payments for update to authenticated using (true) with check (true);

-- Estado de la factura y reglas de anulacion.
create or replace function public.billing_invoice_status()
returns trigger language plpgsql set search_path = '' as $$
declare
  v_paid numeric;
begin
  if tg_op = 'UPDATE' and old.status = 'Anulado' then
    if new.status <> 'Anulado' then
      raise exception 'Una factura anulada no se puede reactivar.';
    end if;
    return new;
  end if;

  select coalesce(sum(amount), 0) into v_paid
  from public.payments where invoice_id = new.id and not anulado;

  if new.status = 'Anulado' then
    if coalesce(trim(new.motivo_anulacion), '') = '' then
      raise exception 'Indica el motivo de anulación de la factura.';
    end if;
    if v_paid > 0 then
      raise exception 'La factura tiene pagos registrados: anúlalos antes de anular la factura.';
    end if;
    new.anulada_at := now();
    new.anulada_por := coalesce(new.anulada_por, auth.uid());
    return new;
  end if;

  if new.amount < v_paid then
    raise exception 'El monto de la factura no puede ser menor a lo ya pagado ($%).', v_paid;
  end if;
  new.status := case
    when v_paid > 0 and v_paid >= new.amount then 'Pagado'
    when v_paid > 0 then 'Parcial'
    else 'Pendiente'
  end;
  return new;
end;
$$;
create trigger trg_billing_invoices_status before insert or update on public.billing_invoices
  for each row execute function public.billing_invoice_status();

create or replace function public.check_payment()
returns trigger language plpgsql set search_path = '' as $$
declare
  v_invoice public.billing_invoices;
  v_paid numeric;
begin
  if tg_op = 'INSERT' then
    select * into v_invoice from public.billing_invoices where id = new.invoice_id for update;
    if v_invoice.status = 'Anulado' then
      raise exception 'No se pueden registrar pagos en una factura anulada.';
    end if;
    select coalesce(sum(amount), 0) into v_paid
    from public.payments where invoice_id = new.invoice_id and not anulado;
    if new.amount > v_invoice.amount - v_paid then
      raise exception 'El pago ($%) supera el saldo pendiente ($%).', new.amount, v_invoice.amount - v_paid;
    end if;
    new.anulado := false;
    new.motivo_anulacion := null;
    new.anulado_por := null;
    new.anulado_at := null;
    return new;
  end if;

  if old.anulado then
    raise exception 'Un pago anulado no se puede modificar.';
  end if;
  if not new.anulado
     or (new.invoice_id, new.amount, new.paid_at, new.method, new.reference, new.notes, new.registered_by)
        is distinct from (old.invoice_id, old.amount, old.paid_at, old.method, old.reference, old.notes, old.registered_by) then
    raise exception 'Los pagos no se editan: anula el pago con un motivo y registra uno nuevo.';
  end if;
  if coalesce(trim(new.motivo_anulacion), '') = '' then
    raise exception 'Indica el motivo de anulación del pago.';
  end if;
  new.anulado_at := now();
  new.anulado_por := coalesce(new.anulado_por, auth.uid());
  return new;
end;
$$;
create trigger trg_payments_check before insert or update on public.payments
  for each row execute function public.check_payment();

-- Cada pago (o su anulacion) recalcula el estado de su factura via trg_billing_invoices_status.
create or replace function public.refresh_invoice_after_payment()
returns trigger language plpgsql set search_path = '' as $$
begin
  update public.billing_invoices set status = status
  where id = new.invoice_id and status <> 'Anulado';
  return null;
end;
$$;
create trigger trg_payments_refresh_invoice after insert or update on public.payments
  for each row execute function public.refresh_invoice_after_payment();

-- Crear la factura y sus items en una sola transaccion; el monto es la suma de los items.
create or replace function public.create_invoice_with_items(p_invoice jsonb, p_items jsonb)
returns public.billing_invoices language plpgsql set search_path = '' as $$
declare
  v_invoice public.billing_invoices;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'La factura debe tener al menos un concepto.';
  end if;

  insert into public.billing_invoices (patient_id, patient_document, patient_name, date, amount, metadata)
  values (
    nullif(p_invoice->>'patient_id', '')::uuid,
    p_invoice->>'patient_document',
    p_invoice->>'patient_name',
    (p_invoice->>'date')::date,
    0,
    p_invoice->'metadata'
  )
  returning * into v_invoice;

  insert into public.invoice_items (invoice_id, patient_procedure_id, description, quantity, unit_price)
  select v_invoice.id,
         nullif(item->>'patient_procedure_id', '')::bigint,
         item->>'description',
         coalesce((item->>'quantity')::numeric, 1),
         coalesce((item->>'unit_price')::numeric, 0)
  from jsonb_array_elements(p_items) as item;

  update public.billing_invoices
  set amount = (select coalesce(sum(total), 0) from public.invoice_items where invoice_id = v_invoice.id)
  where id = v_invoice.id
  returning * into v_invoice;

  return v_invoice;
end;
$$;
revoke execute on function public.create_invoice_with_items(jsonb, jsonb) from public, anon;
grant execute on function public.create_invoice_with_items(jsonb, jsonb) to authenticated;

-- Las facturas no se borran (se anulan): se reemplaza la politica "ALL" por
-- select/insert/update, sin delete.
drop policy billing_invoices_all_authenticated on public.billing_invoices;
create policy billing_invoices_select_authenticated on public.billing_invoices for select to authenticated using (true);
create policy billing_invoices_insert_authenticated on public.billing_invoices for insert to authenticated with check (true);
create policy billing_invoices_update_authenticated on public.billing_invoices for update to authenticated using (true) with check (true);

-- Las facturas que ya estaban marcadas 'Pagado' a mano reciben un pago por su valor,
-- para que el estado calculado a partir de los pagos siga siendo 'Pagado'.
insert into public.payments (invoice_id, amount, paid_at, method, notes, registered_by)
select id, amount, date, 'Otro', 'Pago registrado antes del módulo de pagos (migración).', null
from public.billing_invoices
where status = 'Pagado' and amount > 0;
