create table public.authorized_emails (
  id uuid not null default gen_random_uuid (),
  email text not null,
  full_name text null,
  role text not null default 'user'::text,
  created_by uuid null,
  created_at timestamp with time zone null default now(),
  constraint authorized_emails_pkey primary key (id),
  constraint authorized_emails_email_key unique (email),
  constraint authorized_emails_created_by_fkey foreign KEY (created_by) references auth.users (id),
  constraint authorized_emails_role_check check ((role = any (array['admin'::text, 'user'::text])))
) TABLESPACE pg_default;


create table public.clinical_histories (
  id bigint generated by default as identity not null,
  patient_id text not null,
  doctor text null,
  medio_remision text null,
  fecha timestamp with time zone not null default now(),
  motivo_consulta text null,
  history_data jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint clinical_histories_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists clinical_histories_patient_id_idx on public.clinical_histories using btree (patient_id) TABLESPACE pg_default;

create index IF not exists clinical_histories_fecha_idx on public.clinical_histories using btree (fecha desc) TABLESPACE pg_default;

create index IF not exists clinical_histories_patient_idx on public.clinical_histories using btree (patient_id) TABLESPACE pg_default;





------------------
create table public.doctors (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre text null,
  documento_identidad text null,
  updated_at timestamp with time zone not null default now(),
  apellidos text null,
  especialidad text null,
  correo text null,
  telefono text null,
  registro_profesional text null,
  activo boolean not null default true,
  observaciones text null,
  constraint doctors_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists doctors_documento_identidad_key on public.doctors using btree (documento_identidad) TABLESPACE pg_default;

create unique INDEX IF not exists doctors_correo_key on public.doctors using btree (correo) TABLESPACE pg_default
where
  (correo is not null);

create index IF not exists idx_doctors_nombre on public.doctors using btree (nombre) TABLESPACE pg_default;

create index IF not exists idx_doctors_activo on public.doctors using btree (activo) TABLESPACE pg_default;

create trigger trg_doctors_updated_at BEFORE
update on doctors for EACH row
execute FUNCTION set_updated_at ();


----------------------


create table public.inventory_items (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  name text not null,
  category text null,
  sku text null,
  stock numeric(12, 2) not null default 0,
  min_stock numeric(12, 2) not null default 0,
  unit text not null default 'unidad'::text,
  cost numeric(12, 2) not null default 0,
  supplier text null,
  expiration_date date null,
  active boolean not null default true,
  notes text null,
  constraint inventory_items_pkey primary key (id),
  constraint inventory_items_sku_key unique (sku),
  constraint inventory_items_cost_check check ((cost >= (0)::numeric)),
  constraint inventory_items_min_stock_check check ((min_stock >= (0)::numeric)),
  constraint inventory_items_stock_check check ((stock >= (0)::numeric))
) TABLESPACE pg_default;

create index IF not exists idx_inventory_items_name on public.inventory_items using btree (name) TABLESPACE pg_default;

create index IF not exists idx_inventory_items_category on public.inventory_items using btree (category) TABLESPACE pg_default;

create index IF not exists idx_inventory_items_stock on public.inventory_items using btree (stock) TABLESPACE pg_default;

create index IF not exists idx_inventory_items_active on public.inventory_items using btree (active) TABLESPACE pg_default;

create trigger trg_inventory_items_updated_at BEFORE
update on inventory_items for EACH row
execute FUNCTION set_updated_at ();


-------------------



create table public.laboratory_cases (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  patient_id uuid not null,
  procedure_catalog_id bigint null,
  doctor_id bigint null,
  work_name text not null,
  lab_name text null,
  due_date date null,
  received_date date null,
  delivered_date date null,
  status text not null default 'Pendiente'::text,
  notes text null,
  constraint laboratory_cases_pkey primary key (id),
  constraint laboratory_cases_doctor_id_fkey foreign KEY (doctor_id) references doctors (id) on delete set null,
  constraint laboratory_cases_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE,
  constraint laboratory_cases_procedure_catalog_id_fkey foreign KEY (procedure_catalog_id) references procedure_catalog (id) on delete set null,
  constraint laboratory_cases_status_check check (
    (
      status = any (
        array[
          'Pendiente'::text,
          'En proceso'::text,
          'Entregado'::text,
          'Cancelado'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_laboratory_cases_patient_id on public.laboratory_cases using btree (patient_id) TABLESPACE pg_default;

create index IF not exists idx_laboratory_cases_status on public.laboratory_cases using btree (status) TABLESPACE pg_default;

create index IF not exists idx_laboratory_cases_due_date on public.laboratory_cases using btree (due_date) TABLESPACE pg_default;

create index IF not exists laboratory_cases_patient_idx on public.laboratory_cases using btree (patient_id) TABLESPACE pg_default;

create trigger trg_laboratory_cases_updated_at BEFORE
update on laboratory_cases for EACH row
execute FUNCTION set_updated_at ();




-------------------


create table public.patient_procedures (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  patient_id uuid not null,
  procedure_catalog_id bigint not null,
  doctor_id bigint null,
  tooth_number text null,
  procedure_date date not null default CURRENT_DATE,
  status text not null default 'Pendiente'::text,
  quantity numeric(12, 2) not null default 1,
  unit_price numeric(12, 2) not null default 0,
  total_price numeric GENERATED ALWAYS as ((quantity * unit_price)) STORED (12, 2) null,
  notes text null,
  constraint patient_procedures_pkey primary key (id),
  constraint patient_procedures_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE,
  constraint patient_procedures_doctor_id_fkey foreign KEY (doctor_id) references doctors (id) on delete set null,
  constraint patient_procedures_procedure_catalog_id_fkey foreign KEY (procedure_catalog_id) references procedure_catalog (id),
  constraint patient_procedures_quantity_check check ((quantity > (0)::numeric)),
  constraint patient_procedures_status_check check (
    (
      status = any (
        array[
          'Pendiente'::text,
          'En proceso'::text,
          'Realizado'::text,
          'Cancelado'::text
        ]
      )
    )
  ),
  constraint patient_procedures_unit_price_check check ((unit_price >= (0)::numeric))
) TABLESPACE pg_default;

create index IF not exists idx_patient_procedures_patient_id on public.patient_procedures using btree (patient_id) TABLESPACE pg_default;

create index IF not exists idx_patient_procedures_procedure_catalog_id on public.patient_procedures using btree (procedure_catalog_id) TABLESPACE pg_default;

create index IF not exists idx_patient_procedures_procedure_date on public.patient_procedures using btree (procedure_date desc) TABLESPACE pg_default;

create index IF not exists idx_patient_procedures_status on public.patient_procedures using btree (status) TABLESPACE pg_default;

create trigger trg_patient_procedures_updated_at BEFORE
update on patient_procedures for EACH row
execute FUNCTION set_updated_at ();



--------------------




create table public.patients (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  nombre text null,
  apellidos text null,
  fecha_nacimiento date null,
  direccion text null,
  telefono text null,
  celular text null,
  ocupacion text null,
  sexo text null,
  email text null,
  tipo_sangre text null,
  eps text null,
  tipo_documento text not null,
  numero_documento text not null,
  acudiente_celular text null,
  acudiente_direccion text null,
  acudiente_nombre text null,
  acudiente_parentesco text null,
  edad text null,
  alergias text null,
  medicamentos text null,
  constraint patients_pkey primary key (id),
  constraint patients_numero_documento_key unique (numero_documento),
  constraint patients_tipo_documento_key unique (tipo_documento)
) TABLESPACE pg_default;

create index IF not exists patients_numero_documento_idx on public.patients using btree (numero_documento) TABLESPACE pg_default;

create trigger set_updated_at BEFORE
update on patients for EACH row
execute FUNCTION trg_set_updated_at ();






--------------------



create table public.procedure_catalog (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  code text null,
  name text not null,
  category text null,
  description text null,
  price numeric(12, 2) not null default 0,
  active boolean not null default true,
  constraint procedure_catalog_pkey primary key (id),
  constraint procedure_catalog_code_key unique (code),
  constraint procedure_catalog_price_check check ((price >= (0)::numeric))
) TABLESPACE pg_default;

create index IF not exists idx_procedure_catalog_name on public.procedure_catalog using btree (name) TABLESPACE pg_default;

create index IF not exists idx_procedure_catalog_active on public.procedure_catalog using btree (active) TABLESPACE pg_default;

create trigger trg_procedure_catalog_updated_at BEFORE
update on procedure_catalog for EACH row
execute FUNCTION set_updated_at ();




---------------------


create table public.procedures (
  id uuid not null default gen_random_uuid (),
  patient_id uuid not null,
  procedure_name text not null,
  tooth_number text null,
  cost numeric(10, 2) not null default 0,
  fecha date null default CURRENT_DATE,
  notes text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint procedures_pkey primary key (id),
  constraint procedures_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE,
  constraint procedures_cost_check check ((cost >= (0)::numeric))
) TABLESPACE pg_default;

create index IF not exists idx_procedures_patient_id on public.procedures using btree (patient_id) TABLESPACE pg_default;

create index IF not exists idx_procedures_created_at on public.procedures using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_procedures_name on public.procedures using btree (procedure_name) TABLESPACE pg_default;

create index IF not exists procedures_patient_idx on public.procedures using btree (patient_id) TABLESPACE pg_default;

create trigger trg_procedures_updated_at BEFORE
update on procedures for EACH row
execute FUNCTION set_updated_at ();


----------------------


create table public.profiles (
  id uuid not null,
  email text not null,
  full_name text null,
  role text not null default 'user'::text,
  created_at timestamp with time zone null default now(),
  constraint profiles_pkey primary key (id),
  constraint profiles_email_key unique (email),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint profiles_role_check check ((role = any (array['admin'::text, 'user'::text])))
) TABLESPACE pg_default;

create unique INDEX IF not exists profiles_email_idx on public.profiles using btree (email) TABLESPACE pg_default;



-----------------------


create table public.radiographies (
  id serial not null,
  patient_id uuid null,
  file_path text null,
  file_name text null,
  description text null,
  metadata jsonb null,
  created_at timestamp with time zone not null default now(),
  constraint radiographies_pkey primary key (id),
  constraint radiographies_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists radiographies_patient_idx on public.radiographies using btree (patient_id) TABLESPACE pg_default;

-- Billing invoices table used by the Billing module
-- Includes optional patient_id (UUID FK) and patient_name for legacy/fallback uses
CREATE TABLE IF NOT EXISTS public.billing_invoices (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  patient_id uuid null,
  patient_document text null,
  patient_name text null,
  date date not null,
  amount numeric(12,2) not null default 0,
  status text not null default 'Pendiente'::text,
  metadata jsonb null,
  constraint billing_invoices_pkey primary key (id),
  constraint billing_invoices_status_check check (
    (
      status = any (array['Pagado'::text, 'Pendiente'::text, 'Anulado'::text])
    )
  ),
  constraint billing_invoices_patient_id_fkey foreign key (patient_id) references public.patients(id) on delete set null
);

alter table public.billing_invoices
  add column if not exists patient_document text null;

create index IF not exists idx_billing_invoices_patient_id on public.billing_invoices using btree (patient_id) TABLESPACE pg_default;
create index IF not exists idx_billing_invoices_date on public.billing_invoices using btree (date desc) TABLESPACE pg_default;

-- -----------------------
-- Correcciones añadidas: extensión, funciones de trigger, y ajuste de tipos/constraints
-- No se sobrescribieron líneas existentes; estas sentencias pueden ejecutarse de forma segura

-- Asegurar extensión necesaria para gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Función trigger para mantener updated_at sincronizado
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Alias histórico: algunos triggers llaman a `set_updated_at()`
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Corregir tipo de patient_id en clinical_histories (text -> uuid)
-- Esto asume que los valores existentes en patient_id son UUID en texto; si no, la conversión fallará.
ALTER TABLE public.clinical_histories
  ALTER COLUMN patient_id TYPE uuid USING patient_id::uuid;

-- Añadir la constraint FK si no existe
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'clinical_histories_patient_id_fkey'
      AND table_schema = 'public'
  ) THEN
    EXECUTE 'ALTER TABLE public.clinical_histories
      ADD CONSTRAINT clinical_histories_patient_id_fkey
      FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE';
  END IF;
END;
$$;

-- Nota: si se quiere que `radiographies.patient_id` sea NOT NULL, añade:
-- ALTER TABLE public.radiographies ALTER COLUMN patient_id SET NOT NULL;


-- 17/07/2026
ALTER TABLE public.authorized_emails
ADD COLUMN active boolean NOT NULL DEFAULT true;

-- -----------------------
-- 21/07/2026
-- Storage para radiografías
-- Crear un bucket para guardar archivos de radiografías
INSERT INTO storage.buckets (id, name, public)
VALUES ('radiographies', 'radiographies', true)
ON CONFLICT (id) DO UPDATE
SET public = EXCLUDED.public;

-- Permitir lectura a usuarios autenticados
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Allow authenticated read radiographies'
  ) THEN
    CREATE POLICY "Allow authenticated read radiographies"
    ON storage.objects
    FOR SELECT
    TO authenticated
    USING (bucket_id = 'radiographies');
  END IF;
END;
$$;

-- Permitir subida a usuarios autenticados
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Allow authenticated upload radiographies'
  ) THEN
    CREATE POLICY "Allow authenticated upload radiographies"
    ON storage.objects
    FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'radiographies');
  END IF;
END;
$$;

-- Permitir actualización y borrado si se necesita después
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Allow authenticated update radiographies'
  ) THEN
    CREATE POLICY "Allow authenticated update radiographies"
    ON storage.objects
    FOR UPDATE
    TO authenticated
    USING (bucket_id = 'radiographies')
    WITH CHECK (bucket_id = 'radiographies');
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Allow authenticated delete radiographies'
  ) THEN
    CREATE POLICY "Allow authenticated delete radiographies"
    ON storage.objects
    FOR DELETE
    TO authenticated
    USING (bucket_id = 'radiographies');
  END IF;
END;
$$;

-- 05/08/2026
-- Añadir columna odontograma a clinical_histories
ALTER TABLE clinical_histories ADD COLUMN odontograma JSONB;

-- 06/08/2026
-- Asociar cada radiografía a la historia clínica donde fue registrada
ALTER TABLE public.radiographies
  ADD COLUMN IF NOT EXISTS clinical_history_id bigint null;

CREATE INDEX IF NOT EXISTS radiographies_clinical_history_idx
  ON public.radiographies (clinical_history_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'radiographies_patient_id_fkey'
      AND table_schema = 'public'
  ) THEN
    ALTER TABLE public.radiographies
      ADD CONSTRAINT radiographies_patient_id_fkey
      FOREIGN KEY (patient_id)
      REFERENCES public.patients(id)
      ON DELETE CASCADE;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'radiographies_clinical_history_id_fkey'
      AND table_schema = 'public'
  ) THEN
    ALTER TABLE public.radiographies
      ADD CONSTRAINT radiographies_clinical_history_id_fkey
      FOREIGN KEY (clinical_history_id)
      REFERENCES public.clinical_histories(id)
      ON DELETE CASCADE;
  END IF;
END;
$$;


----------------------


create table public.message_templates (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  channel text not null default 'Email',
  subject text null,
  body text not null,
  active boolean not null default true,
  constraint message_templates_pkey primary key (id),
  constraint message_templates_channel_check check (channel = any (array['Email'::text,'SMS'::text,'WhatsApp'::text]))
) TABLESPACE pg_default;

create trigger trg_message_templates_updated_at
before update on public.message_templates
for each row execute function set_updated_at();

alter table public.message_templates enable row level security;

create policy message_templates_all_authenticated
on public.message_templates
for all
to authenticated
using (true)
with check (true);


----------------------


create table public.informed_consents (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  patient_id uuid not null,
  doctor_id bigint null,
  procedure_catalog_id bigint null,
  content text not null,
  patient_signature_name text not null,
  signed_at timestamptz not null default now(),
  registered_by uuid null,
  constraint informed_consents_pkey primary key (id),
  constraint informed_consents_patient_id_fkey foreign key (patient_id) references public.patients (id) on delete cascade,
  constraint informed_consents_doctor_id_fkey foreign key (doctor_id) references public.doctors (id) on delete set null,
  constraint informed_consents_procedure_catalog_id_fkey foreign key (procedure_catalog_id) references public.procedure_catalog (id) on delete set null,
  constraint informed_consents_registered_by_fkey foreign key (registered_by) references auth.users (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_informed_consents_patient_id on public.informed_consents using btree (patient_id) TABLESPACE pg_default;

alter table public.informed_consents enable row level security;

create policy informed_consents_all_authenticated
on public.informed_consents
for all
to authenticated
using (true)
with check (true);


----------------------


create table public.data_rectification_requests (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  patient_id uuid not null,
  request_type text not null default 'Rectificación',
  description text not null,
  status text not null default 'Pendiente',
  resolution_notes text null,
  resolved_at timestamptz null,
  constraint data_rectification_requests_pkey primary key (id),
  constraint data_rectification_requests_patient_id_fkey foreign key (patient_id) references public.patients (id) on delete cascade,
  constraint data_rectification_requests_type_check check (request_type = any (array['Rectificación'::text,'Actualización'::text,'Supresión'::text,'Revocatoria de autorización'::text])),
  constraint data_rectification_requests_status_check check (status = any (array['Pendiente'::text,'En proceso'::text,'Resuelta'::text,'Rechazada'::text]))
) TABLESPACE pg_default;

create index IF not exists idx_data_rectification_requests_patient_id on public.data_rectification_requests using btree (patient_id) TABLESPACE pg_default;

create trigger trg_data_rectification_requests_updated_at
before update on public.data_rectification_requests
for each row execute function set_updated_at();

alter table public.data_rectification_requests enable row level security;

create policy data_rectification_requests_all_authenticated
on public.data_rectification_requests
for all
to authenticated
using (true)
with check (true);


----------------------


-- CU-20: autorizacion de tratamiento de datos personales, capturada en el registro del paciente
alter table public.patients
  add column if not exists autorizacion_datos boolean not null default false,
  add column if not exists autorizacion_datos_fecha timestamptz null;


----------------------


-- system_settings (tabla preexistente, definicion documentada aqui por primera vez)
-- create table public.system_settings (
--   id bigint generated by default as identity not null,
--   appointment_duration_minutes integer not null default 20,
--   business_hours_start time without time zone not null default '08:00:00',
--   business_hours_end time without time zone not null default '18:00:00',
--   updated_at timestamptz not null default now(),
--   constraint system_settings_pkey primary key (id)
-- );

-- RLS estaba deshabilitado (tabla totalmente expuesta a anon/authenticated). Se habilito
-- con el mismo patron "authenticated, ALL" usado en el resto del esquema.
alter table public.system_settings enable row level security;

create policy system_settings_all_authenticated
on public.system_settings
for all
to authenticated
using (true)
with check (true);


----------------------


-- CU-06/07/08/17/22: espejo de citas de Google Calendar en Supabase. Las citas viven
-- en Google Calendar (unica fuente de verdad para horarios); esta tabla existe porque
-- ningun proceso de servidor (cron/Edge Function) puede leer Google Calendar sin un
-- refresh token persistido, que hoy no se guarda en ningun lado (solo existe
-- session.provider_token, efimero, en el navegador de quien inicio sesion). Se
-- sincroniza en el cliente (CalendarCtrl.js) cada vez que se crea/reprograma/cancela
-- una cita desde la app, y directamente desde el webhook de WhatsApp para
-- solicitudes/cancelaciones que aun no existen en Google Calendar.
create extension if not exists pg_cron;
create extension if not exists pg_net;

create table public.appointments (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  patient_id uuid null,
  google_event_id text null,
  start_at timestamptz null,
  end_at timestamptz null,
  service_type text null,
  notes text null,
  status text not null default 'Confirmada',
  source text not null default 'App',
  requester_phone text null,
  reminder_sent_at timestamptz null,
  constraint appointments_pkey primary key (id),
  constraint appointments_google_event_id_key unique (google_event_id),
  constraint appointments_patient_id_fkey foreign key (patient_id) references public.patients (id) on delete set null,
  constraint appointments_status_check check (status = any (array['Solicitada'::text,'Confirmada'::text,'Cancelación solicitada'::text,'Cancelada'::text])),
  constraint appointments_source_check check (source = any (array['App'::text,'WhatsApp'::text]))
) TABLESPACE pg_default;

create index IF not exists idx_appointments_patient_id on public.appointments using btree (patient_id) TABLESPACE pg_default;
create index IF not exists idx_appointments_start_at on public.appointments using btree (start_at) TABLESPACE pg_default;
create index IF not exists idx_appointments_status on public.appointments using btree (status) TABLESPACE pg_default;

create trigger trg_appointments_updated_at
before update on public.appointments
for each row execute function set_updated_at();

alter table public.appointments enable row level security;

create policy appointments_all_authenticated
on public.appointments
for all
to authenticated
using (true)
with check (true);


----------------------


-- CU-16/17/21/22/23: bitacora de mensajes de WhatsApp (entrantes y salientes). Cualquier
-- parte de la app que necesite enviar un mensaje inserta una fila 'outbound'/'pending' aqui;
-- la Edge Function process-whatsapp-queue (cron cada 5 min) la entrega via Twilio cuando
-- haya credenciales configuradas, o la marca 'no_provider' si no las hay.
create table public.whatsapp_messages (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  sent_at timestamptz null,
  direction text not null,
  phone text not null,
  patient_id uuid null,
  appointment_id bigint null,
  template_id bigint null,
  body text not null,
  status text not null default 'pending',
  provider_message_id text null,
  error text null,
  constraint whatsapp_messages_pkey primary key (id),
  constraint whatsapp_messages_patient_id_fkey foreign key (patient_id) references public.patients (id) on delete set null,
  constraint whatsapp_messages_appointment_id_fkey foreign key (appointment_id) references public.appointments (id) on delete set null,
  constraint whatsapp_messages_template_id_fkey foreign key (template_id) references public.message_templates (id) on delete set null,
  constraint whatsapp_messages_direction_check check (direction = any (array['inbound'::text,'outbound'::text])),
  constraint whatsapp_messages_status_check check (status = any (array['pending'::text,'sent'::text,'failed'::text,'received'::text,'no_provider'::text]))
) TABLESPACE pg_default;

create index IF not exists idx_whatsapp_messages_status on public.whatsapp_messages using btree (status) TABLESPACE pg_default;
create index IF not exists idx_whatsapp_messages_phone on public.whatsapp_messages using btree (phone) TABLESPACE pg_default;
create index IF not exists idx_whatsapp_messages_patient_id on public.whatsapp_messages using btree (patient_id) TABLESPACE pg_default;

alter table public.whatsapp_messages enable row level security;

create policy whatsapp_messages_all_authenticated
on public.whatsapp_messages
for all
to authenticated
using (true)
with check (true);

-- Cron: dispara las Edge Functions desplegadas en supabase/functions/*.
-- queue-appointment-reminders: cada hora, revisa citas confirmadas 23-25h en el futuro
--   sin recordatorio enviado y encola un mensaje en whatsapp_messages.
-- process-whatsapp-queue: cada 5 minutos, entrega los mensajes 'pending' via Twilio.
-- Ambas usan la anon key (JWT publico) porque las funciones corren con verify_jwt=true
-- y usan SUPABASE_SERVICE_ROLE_KEY (inyectada automaticamente por Supabase) por dentro
-- para saltarse RLS.
select cron.schedule(
  'queue-appointment-reminders',
  '0 * * * *',
  $$
  select net.http_post(
    url := 'https://czfuquhkjuhbwnkbgkze.supabase.co/functions/v1/queue-appointment-reminders',
    headers := '{"Authorization": "Bearer <anon key>", "Content-Type": "application/json"}'::jsonb,
    body := '{}'::jsonb
  );
  $$
);

select cron.schedule(
  'process-whatsapp-queue',
  '*/5 * * * *',
  $$
  select net.http_post(
    url := 'https://czfuquhkjuhbwnkbgkze.supabase.co/functions/v1/process-whatsapp-queue',
    headers := '{"Authorization": "Bearer <anon key>", "Content-Type": "application/json"}'::jsonb,
    body := '{}'::jsonb
  );
  $$
);
